[package]
name = "redirect"
version = "0.0.0"
authors = ["Luxko <liarluxlux@gmail.com>"]
license = "Apache-2.0"
keywords = ["graphics"]

[dependencies]
winapi = "0.2"
d3d12-sys = "*"
dxguid-sys = "*"
dxgi-sys = "*"
bitflags = "0.9"
smallvec = "0.4"

[[example]]
name = "initialize"
path = "examples/initialize.rs"

[dev-dependencies]
winit = "0.6"
